import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Search,ShieldCheck,Sun,Moon,Bookmark,ExternalLink,Menu,X,Star,Library,User,ChevronLeft,ChevronRight,BookOpen,LogOut,Trash2,Plus,LoaderCircle}from'lucide-react';
import'./styles.css';

type Link={site:string,url:string,type:string};
type Media={id:number,title:{english?:string;romaji:string;native?:string};kind:string;format:string;status:string;description:string;genres:string[];chapters?:number;coverImage:{large:string;color?:string};averageScore:number;popularity:number;siteUrl:string;externalLinks:Link[]};
type Saved={id:number;title:string;cover:string;kind:string;status:string;progress:number;chapters?:number;updatedAt:string};
type Me={signedIn:boolean;email:string;name:string;signInUrl:string;signOutUrl:string;authConfigured?:boolean};
type Rating={average:number;count:number;mine?:number};
const verifiedDomains=new Set(['webtoons.com','www.webtoons.com','tapas.io','www.tapas.io','mangaplus.shueisha.co.jp','comikey.com','www.comikey.com','tappytoon.com','www.tappytoon.com','lezhinus.com','www.lezhinus.com','manta.net','www.manta.net','viz.com','www.viz.com','kodansha.us','www.kodansha.us','crunchyroll.com','www.crunchyroll.com']);
const titleOf=(m:Media)=>m.title.english||m.title.romaji;
const clean=(s='')=>s.replace(/<[^>]+>/g,'').replace(/\n/g,' ').slice(0,420);
const sourceInfo=(link:Link)=>{try{const domain=new URL(link.url).hostname.toLowerCase();return{verified:verifiedDomains.has(domain),domain}}catch{return{verified:false,domain:''}}};

function App(){
 const[dark,setDark]=useState(false),[menu,setMenu]=useState(false),[tab,setTab]=useState<'discover'|'library'>('discover'),[query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[page,setPage]=useState(1),[media,setMedia]=useState<Media[]>([]),[active,setActive]=useState<Media|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[me,setMe]=useState<Me|null>(null),[library,setLibrary]=useState<Saved[]>([]),[ratings,setRatings]=useState<Record<number,Rating>>({});
 useEffect(()=>{const v=localStorage.getItem('toontrail-theme');setDark(v?v==='dark':matchMedia('(prefers-color-scheme:dark)').matches);fetch('/api/me').then(r=>r.json()).then(setMe)},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('toontrail-theme',dark?'dark':'light')},[dark]);
 useEffect(()=>{loadCatalog()},[submitted,page]);
 useEffect(()=>{if(me?.signedIn)loadLibrary()},[me?.signedIn]);
 async function loadCatalog(){setLoading(true);try{const r=await fetch(`/api/catalog?page=${page}&q=${encodeURIComponent(submitted)}`);const d=await r.json();if(!r.ok)throw Error(d.error);setMedia(d.media||[]);const ids=(d.media||[]).map((m:Media)=>m.id).join(',');if(ids)fetch(`/api/ratings?ids=${ids}`).then(x=>x.json()).then(x=>setRatings(v=>({...v,...x.ratings})));}catch(e){setNotice(e instanceof Error?e.message:'Catalogue unavailable')}finally{setLoading(false)}}
 async function loadLibrary(){const r=await fetch('/api/library');if(r.ok)setLibrary((await r.json()).items||[])}
 const savedIds=useMemo(()=>new Set(library.map(x=>x.id)),[library]);
 function requireSignIn(){if(!me?.signedIn){if(me?.authConfigured===false){setNotice('Google sign-in is being configured. Please try again soon.');return false}setNotice('Sign in to save titles, update progress, and rate stories.');setTimeout(()=>location.href=me?.signInUrl||'/auth/google',700);return false}return true}
 async function saveMedia(m:Media,status='PLANNING',progress=0){if(!requireSignIn())return;const body={id:m.id,title:titleOf(m),cover:m.coverImage.large,kind:m.kind,status,progress,chapters:m.chapters};const r=await fetch('/api/library',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(r.ok){await loadLibrary();setNotice(status==='PLANNING'?'Added to your library':'Progress updated')}else setNotice((await r.json()).error)}
 async function removeSaved(id:number){await fetch(`/api/library/${id}`,{method:'DELETE'});await loadLibrary();setNotice('Removed from library')}
 async function updateSaved(item:Saved,patch:Partial<Saved>){const r=await fetch('/api/library',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...item,...patch})});if(r.ok){await loadLibrary();setNotice('Library updated')}}
 async function rate(id:number,score:number){if(!requireSignIn())return;const r=await fetch('/api/rating',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mediaId:id,score})});if(r.ok){const d=await fetch(`/api/ratings?ids=${id}`).then(x=>x.json());setRatings(v=>({...v,...d.ratings}));setNotice('Rating saved')}}
 async function openMedia(m:Media){setActive(m);try{const r=await fetch(`/api/catalog/${m.id}`);if(r.ok)setActive((await r.json()).media)}catch{}}
 const search=(e:React.FormEvent)=>{e.preventDefault();setPage(1);setSubmitted(query.trim())};
 return <div className="app">
  <header><button className="brand" onClick={()=>{setTab('discover');scrollTo(0,0)}}><span>TT</span>ToonTrail</button><nav className={menu?'open':''}><button className={tab==='discover'?'active':''} onClick={()=>{setTab('discover');setMenu(false)}}>Discover</button><button className={tab==='library'?'active':''} onClick={()=>{setTab('library');setMenu(false)}}>My Library {library.length>0&&<i>{library.length}</i>}</button><a href="#how">How it works</a></nav><div className="head-actions"><button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle dark mode">{dark?<Sun/>:<Moon/>}</button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>{me?.signedIn?<button className="account" onClick={()=>location.href=me.signOutUrl} title="Sign out"><User/><span>{me.name||'Signed in'}</span><LogOut/></button>:<button className="signin" onClick={requireSignIn}>{me?.authConfigured===false?'Sign-in setup pending':'Continue with Google'}</button>}</div></header>
  {notice&&<button className="toast" onClick={()=>setNotice('')}>{notice}<X/></button>}
  <main>{tab==='discover'?<>
   <section className="hero"><div className="eyebrow"><ShieldCheck/> Official-source discovery</div><h1>Every story.<br/><em>One safe path.</em></h1><p>Search a real global catalogue of manga, manhwa, and manhua. Save your place, organise your library, rate stories, and follow clearly labelled reading links.</p><form className="searchbox" onSubmit={search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search any title, alias, or original name"/><button>Search catalogue</button></form><div className="trust"><span><ShieldCheck/>Verified-link labels</span><span><Library/>Persistent library</span><span><Star/>Reader ratings</span></div></section>
   <section className="catalog"><div className="section-head"><div><span className="kicker">{submitted?'Search results':'Popular now'}</span><h2>{submitted?`Results for “${submitted}”`:'Explore the catalogue'}</h2></div>{submitted&&<button className="text-btn" onClick={()=>{setQuery('');setSubmitted('');setPage(1)}}><X/>Clear search</button>}</div>
    {loading?<div className="loading"><LoaderCircle/>Finding stories…</div>:<div className="catalog-grid">{media.map(m=><article className="media-card" key={m.id}><button className="poster" onClick={()=>openMedia(m)}>{m.coverImage.large?<img src={m.coverImage.large} alt=""/>:<span className="cover-art"><b>{titleOf(m).split(' ').slice(0,2).map(x=>x[0]).join('')}</b></span>}<span>{m.kind}</span></button><div className="media-copy"><div><span className="type">{m.format?.replaceAll('_',' ')}</span><button className="bookmark" onClick={()=>savedIds.has(m.id)?removeSaved(m.id):saveMedia(m)} aria-label={savedIds.has(m.id)?'Remove bookmark':'Bookmark'}><Bookmark fill={savedIds.has(m.id)?'currentColor':'none'}/></button></div><button className="title-link" onClick={()=>openMedia(m)}>{titleOf(m)}</button><p>{m.title.native||m.title.romaji}</p><div className="score"><Star fill="currentColor"/> {ratings[m.id]?.average||'—'} <small>{ratings[m.id]?.count?`(${ratings[m.id].count} readers)`:'Not yet rated'}</small></div></div></article>)}</div>}
    <div className="pagination"><button disabled={page===1} onClick={()=>{setPage(p=>p-1);scrollTo(0,500)}}><ChevronLeft/>Previous</button><span>Page {page}</span><button onClick={()=>{setPage(p=>p+1);scrollTo(0,500)}}>Next<ChevronRight/></button></div>
   </section></>:<LibraryView me={me} items={library} onSignIn={requireSignIn} onUpdate={updateSaved} onRemove={removeSaved}/>} 
   <section className="how" id="how"><span className="kicker">Built for a proper beta</span><h2>Discovery, decisions, and progress in one place.</h2><div className="steps"><div><b>01</b><h3>Search real titles</h3><p>Find works by English, romanised, or native names across manga, manhwa, and manhua.</p></div><div><b>02</b><h3>Choose transparently</h3><p>Every reading link is labelled verified or unverified so users can make an informed choice.</p></div><div><b>03</b><h3>Build your library</h3><p>Sign in to bookmark, organise, rate, and continue from the chapter you last recorded.</p></div></div></section>
  </main>
  {active&&<Detail media={active} saved={savedIds.has(active.id)} rating={ratings[active.id]} onClose={()=>setActive(null)} onSave={saveMedia} onRemove={removeSaved} onRate={rate}/>} 
 </div>
}

function LibraryView({me,items,onSignIn,onUpdate,onRemove}:{me:Me|null,items:Saved[],onSignIn:()=>boolean,onUpdate:(i:Saved,p:Partial<Saved>)=>void,onRemove:(id:number)=>void}){if(!me?.signedIn)return <section className="empty-library"><Library/><span className="kicker">Your personal space</span><h1>Sign in to build your library.</h1><p>Bookmarks, reading status, and chapter progress will sync with your ToonTrail account.</p><button className="signin" onClick={onSignIn}>{me?.authConfigured===false?'Sign-in setup pending':'Continue with Google'}</button></section>;return <section className="library-page"><div className="section-head"><div><span className="kicker">Synced to your account</span><h1>My Library</h1></div><span>{items.length} saved titles</span></div>{items.length===0?<div className="no-items"><BookOpen/><h2>Your shelf is waiting.</h2><p>Bookmark a title from Discover to add it here.</p></div>:<div className="library-list">{items.map(i=><article key={i.id}>{i.cover?<img src={i.cover} alt=""/>:<div className="library-cover">{i.title.split(' ').slice(0,2).map(x=>x[0]).join('')}</div>}<div><span className="type">{i.kind}</span><h3>{i.title}</h3><label>Status<select value={i.status} onChange={e=>onUpdate(i,{status:e.target.value})}><option value="PLANNING">Plan to read</option><option value="READING">Reading</option><option value="COMPLETED">Completed</option><option value="PAUSED">Paused</option><option value="DROPPED">Dropped</option></select></label></div><label>Current chapter<input type="number" min="0" max={i.chapters||99999} value={i.progress} onChange={e=>onUpdate(i,{progress:Number(e.target.value),status:Number(e.target.value)>0?'READING':i.status})}/><small>{i.chapters?`of ${i.chapters}`:'Enter your progress'}</small></label><button className="delete" onClick={()=>onRemove(i.id)}><Trash2/>Remove</button></article>)}</div>}</section>}

function Detail({media,saved,rating,onClose,onSave,onRemove,onRate}:{media:Media,saved:boolean,rating?:Rating,onClose:()=>void,onSave:(m:Media,s?:string,p?:number)=>void,onRemove:(id:number)=>void,onRate:(id:number,s:number)=>void}){const links=media.externalLinks||[];return <div className="overlay" onClick={onClose}><aside className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><div className="detail-hero">{media.coverImage.large?<img src={media.coverImage.large} alt=""/>:<div className="detail-cover">{titleOf(media).split(' ').slice(0,2).map(x=>x[0]).join('')}</div>}<div><span className="type">{media.kind} · {media.status?.replaceAll('_',' ')}</span><h2>{titleOf(media)}</h2><p className="aliases">{media.title.native} · {media.title.romaji}</p><div className="tags">{media.genres.slice(0,5).map(g=><span key={g}>{g}</span>)}</div></div></div><p>{clean(media.description)||'No description is currently available.'}</p><div className="rating-box"><div><b>Your rating</b><small>{rating?.count?`${rating.average}/5 from ${rating.count} ToonTrail reader${rating.count===1?'':'s'}`:'Be the first ToonTrail reader to rate this'}</small></div><div className="stars">{[1,2,3,4,5].map(s=><button key={s} onClick={()=>onRate(media.id,s)} aria-label={`${s} stars`}><Star fill={(rating?.mine||0)>=s?'currentColor':'none'}/></button>)}</div></div><h3>Verified places to read</h3>{links.map((link,i)=>{const info=sourceInfo(link);return <div className="source" key={link.url}><div className="rank">{i+1}</div><div><b>{link.site}</b><small>{info.domain} · {link.type||'Official resource'}</small></div><span className={info.verified?'verified':'unverified'}>{info.verified?<><ShieldCheck/>Verified provider</>:<>External link</>}</span><a href={link.url} target="_blank" rel="noopener noreferrer">Open<ExternalLink/></a></div>})}<p className="link-note"><ShieldCheck/> “Verified provider” confirms the domain belongs to a recognised publisher or licensed platform. Availability and included chapters may vary by region.</p><button className="save" onClick={()=>saved?onRemove(media.id):onSave(media)}>{saved?'Remove from My Library':'Add to My Library'}</button></aside></div>}

createRoot(document.getElementById('root')!).render(<App/>);
